# This is a basic workflow to help you get started with Actions

name: Unit testing in 🐍3.7/8/9/10

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost/ci_db_test
          TEST_DATABASE_ASYNC_URL: postgresql+asyncpg://postgres:postgres@localhost/ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - checkout
      - run: sudo apt-get  update
      - run: printenv
      - run: sudo pip install setuptools-rust
      - run: sudo python -m pip install --upgrade pip
      - run: sudo pip install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -r requirements.txt
      - run: coverage run -m pytest ./tests/test_implementations
      - run: coveralls
